-- =============================================
-- 创建红包任务相关表
-- 版本：20250301_001
-- =============================================

-- 1. 红包任务表
CREATE TABLE IF NOT EXISTS `advn_red_packet_task` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '红包ID',
    `name` VARCHAR(100) NOT NULL COMMENT '红包名称',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '红包描述',
    `icon` VARCHAR(500) DEFAULT NULL COMMENT '红包图标',
    `images` TEXT DEFAULT NULL COMMENT '任务宣传图(JSON数组)',
    `task_type` VARCHAR(30) NOT NULL COMMENT '任务类型',
    `task_url` VARCHAR(500) DEFAULT NULL COMMENT '任务跳转链接',
    `task_params` TEXT DEFAULT NULL COMMENT '任务参数(JSON)',
    `total_amount` DECIMAL(18,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '红包总金额(金币)',
    `total_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '红包总数量',
    `remain_amount` DECIMAL(18,2) UNSIGNED DEFAULT 0 COMMENT '剩余金额',
    `remain_count` INT UNSIGNED DEFAULT 0 COMMENT '剩余数量',
    `single_amount` DECIMAL(18,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个红包金额',
    `min_amount` DECIMAL(18,2) UNSIGNED DEFAULT 0 COMMENT '最小金额',
    `max_amount` DECIMAL(18,2) UNSIGNED DEFAULT 0 COMMENT '最大金额',
    `amount_type` VARCHAR(20) DEFAULT 'fixed' COMMENT '金额类型',
    `required_duration` INT UNSIGNED DEFAULT 0 COMMENT '要求时长(秒)',
    `required_progress` TINYINT UNSIGNED DEFAULT 100 COMMENT '要求进度(%)',
    `required_count` INT UNSIGNED DEFAULT 1 COMMENT '要求次数',
    `verify_method` VARCHAR(30) DEFAULT 'auto' COMMENT '验证方式',
    `verify_params` TEXT DEFAULT NULL COMMENT '验证参数(JSON)',
    `user_limit` INT UNSIGNED DEFAULT 1 COMMENT '每人可领取次数',
    `daily_limit` INT UNSIGNED DEFAULT 0 COMMENT '每日限制领取次数',
    `new_user_only` TINYINT UNSIGNED DEFAULT 0 COMMENT '仅限新用户',
    `new_user_days` INT UNSIGNED DEFAULT 7 COMMENT '新用户定义(天数)',
    `user_level_min` TINYINT UNSIGNED DEFAULT 1 COMMENT '最低用户等级',
    `user_level_max` TINYINT UNSIGNED DEFAULT 255 COMMENT '最高用户等级',
    `vip_only` TINYINT UNSIGNED DEFAULT 0 COMMENT '仅限VIP',
    `audit_type` VARCHAR(20) DEFAULT 'auto' COMMENT '审核方式',
    `audit_timeout` INT UNSIGNED DEFAULT 86400 COMMENT '审核超时时间(秒)',
    `need_screenshot` TINYINT UNSIGNED DEFAULT 0 COMMENT '需要上传截图',
    `need_device_info` TINYINT UNSIGNED DEFAULT 1 COMMENT '需要设备信息',
    `start_time` INT UNSIGNED DEFAULT NULL COMMENT '开始时间',
    `end_time` INT UNSIGNED DEFAULT NULL COMMENT '结束时间',
    `expire_hours` INT UNSIGNED DEFAULT 24 COMMENT '领取后有效期(小时)',
    `relation_type` VARCHAR(30) DEFAULT NULL COMMENT '关联类型',
    `relation_id` INT UNSIGNED DEFAULT NULL COMMENT '关联ID',
    `category_id` INT UNSIGNED DEFAULT NULL COMMENT '任务分类ID',
    `view_count` INT UNSIGNED DEFAULT 0 COMMENT '浏览次数',
    `join_count` INT UNSIGNED DEFAULT 0 COMMENT '参与次数',
    `complete_count` INT UNSIGNED DEFAULT 0 COMMENT '完成次数',
    `receive_count` INT UNSIGNED DEFAULT 0 COMMENT '已领取人数',
    `receive_amount` DECIMAL(18,2) UNSIGNED DEFAULT 0 COMMENT '已发放金额',
    `audit_pending_count` INT UNSIGNED DEFAULT 0 COMMENT '待审核数量',
    `audit_reject_count` INT UNSIGNED DEFAULT 0 COMMENT '已拒绝数量',
    `sort` INT UNSIGNED DEFAULT 0 COMMENT '排序',
    `is_hot` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否热门',
    `is_recommend` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否推荐',
    `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0=禁用, 1=启用, 2=已结束, 3=已抢完',
    `createtime` INT UNSIGNED DEFAULT NULL COMMENT '创建时间',
    `updatetime` INT UNSIGNED DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_task_type` (`task_type`),
    KEY `idx_status` (`status`),
    KEY `idx_time_range` (`start_time`, `end_time`),
    KEY `idx_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='红包任务表';

-- 2. 任务参与记录表
CREATE TABLE IF NOT EXISTS `advn_task_participation` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    `task_id` INT UNSIGNED NOT NULL COMMENT '红包任务ID',
    `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
    `order_no` VARCHAR(32) NOT NULL COMMENT '参与订单号',
    `task_type` VARCHAR(30) NOT NULL COMMENT '任务类型',
    `task_name` VARCHAR(100) DEFAULT NULL COMMENT '任务名称快照',
    `task_url` VARCHAR(500) DEFAULT NULL COMMENT '任务链接快照',
    `status` TINYINT UNSIGNED DEFAULT 0 COMMENT '状态',
    `start_time` INT UNSIGNED DEFAULT NULL COMMENT '开始时间',
    `end_time` INT UNSIGNED DEFAULT NULL COMMENT '完成时间',
    `duration` INT UNSIGNED DEFAULT 0 COMMENT '实际耗时(秒)',
    `progress` TINYINT UNSIGNED DEFAULT 0 COMMENT '完成进度(%)',
    `audit_type` VARCHAR(20) DEFAULT 'auto' COMMENT '审核方式',
    `audit_status` TINYINT UNSIGNED DEFAULT 0 COMMENT '审核状态',
    `audit_time` INT UNSIGNED DEFAULT NULL COMMENT '审核时间',
    `audit_admin_id` INT UNSIGNED DEFAULT NULL COMMENT '审核管理员ID',
    `audit_admin_name` VARCHAR(50) DEFAULT NULL COMMENT '审核管理员名称',
    `audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '审核备注',
    `reject_reason` VARCHAR(200) DEFAULT NULL COMMENT '拒绝原因',
    `reward_coin` DECIMAL(18,2) UNSIGNED DEFAULT 0 COMMENT '奖励金币',
    `reward_status` TINYINT UNSIGNED DEFAULT 0 COMMENT '发放状态',
    `reward_time` INT UNSIGNED DEFAULT NULL COMMENT '发放时间',
    `ip` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    `device_id` VARCHAR(100) DEFAULT NULL COMMENT '设备ID',
    `device_info` TEXT DEFAULT NULL COMMENT '设备信息(JSON)',
    `app_version` VARCHAR(20) DEFAULT NULL COMMENT 'APP版本',
    `platform` VARCHAR(20) DEFAULT NULL COMMENT '平台',
    `screenshot_urls` TEXT DEFAULT NULL COMMENT '截图URLs(JSON)',
    `proof_data` TEXT DEFAULT NULL COMMENT '证明数据(JSON)',
    `extra_data` TEXT DEFAULT NULL COMMENT '额外数据(JSON)',
    `createtime` INT UNSIGNED DEFAULT NULL COMMENT '创建时间',
    `updatetime` INT UNSIGNED DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_task_id` (`task_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务参与记录表';

-- 3. 任务分类表
CREATE TABLE IF NOT EXISTS `advn_task_category` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分类ID',
    `name` VARCHAR(50) NOT NULL COMMENT '分类名称',
    `icon` VARCHAR(200) DEFAULT NULL COMMENT '分类图标',
    `description` VARCHAR(200) DEFAULT NULL COMMENT '分类描述',
    `sort` INT UNSIGNED DEFAULT 0 COMMENT '排序',
    `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态',
    `createtime` INT UNSIGNED DEFAULT NULL,
    `updatetime` INT UNSIGNED DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务分类表';

-- 插入测试数据
INSERT INTO `advn_red_packet_task` (`name`, `description`, `task_type`, `total_amount`, `total_count`, `single_amount`, `status`, `createtime`) VALUES
('下载抖音极速版', '下载并安装抖音极速版App，打开运行30秒即可获得奖励', 'download_app', 100000, 100, 1000, 1, UNIX_TIMESTAMP()),
('跳转拼多多小程序', '跳转拼多多小程序浏览商品30秒', 'mini_program', 50000, 200, 250, 1, UNIX_TIMESTAMP()),
('玩游戏领红包', '玩游戏达到指定时长(5分钟)即可领取红包', 'play_game', 500000, 1000, 500, 1, UNIX_TIMESTAMP());
