# 定时任务进程配置

[program:scheduler]
command=php /var/www/html/think schedule:run
autostart=true
autorestart=false
startsecs=0
startretries=0
stdout_logfile=/var/log/supervisor/scheduler.log
stderr_logfile=/var/log/supervisor/scheduler_error.log
user=www-data
priority=50
